spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

server:
  base:
    url: http://localhost:8080

